const http=require('node:http'),fs=require('node:fs'),path=require('node:path');
const root=__dirname,file=path.join(process.env.DEMO_DATA_DIR||path.join(root,'data'),'demo.json');
const initial={requests:[{id:'REQ-1001',service:'Audit',title:'Supplier quality system review',company:'Sample Energy Components',status:'Scheduled',date:'2026-10-12'}],findings:[{id:'F-101',title:'Supplier evaluation record requires review',engagement:'REQ-1001',severity:'Minor',status:'Open',action:'Assign a document owner and review the sample evaluation record.',history:[{date:'2026-09-29T10:00:00Z',status:'Open',note:'Synthetic finding created for demonstration.'}]}],documents:[{id:'DOC-01',title:'Quality manual',version:'2.1',status:'In review',owner:'Demo quality team'},{id:'DOC-02',title:'Supplier evaluation procedure',version:'1.3',status:'Approved',owner:'Demo operations team'}],training:[{id:'TR-01',title:'Quality system foundations',progress:40},{id:'TR-02',title:'Internal audit practice',progress:0}]};
fs.mkdirSync(path.dirname(file),{recursive:true});if(!fs.existsSync(file))fs.writeFileSync(file,JSON.stringify(initial,null,2));
const read=()=>JSON.parse(fs.readFileSync(file,'utf8'));const save=d=>fs.writeFileSync(file,JSON.stringify(d,null,2));
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(data));};
const text=(v,max=300)=>typeof v==='string'?v.trim().slice(0,max):'';
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://localhost');
 if(url.pathname==='/api/state'&&req.method==='GET')return json(res,200,read());
 if(url.pathname==='/reports/sample-inspection.txt'){res.writeHead(200,{'Content-Type':'text/plain; charset=utf-8','Content-Disposition':'attachment; filename="sample-inspection-report.txt"'});return res.end('UNOFFICIAL TIEC REVIEW CONCEPT — SYNTHETIC INSPECTION REPORT\n\nReport: DEMO-INS-001\nAsset: Sample fabricated assembly\nScope: Demonstration vendor/source inspection workflow\nResult: Sample documentation review complete; illustrative follow-up required.\n\nThis is fictional demonstration data, not a certification or actual inspection.');}
 if(req.method==='POST'&&url.pathname.startsWith('/api/')){
 if(req.headers.origin){let origin;try{origin=new URL(req.headers.origin);}catch{return json(res,403,{error:'Origin is not allowed.'});}if(!['http:','https:'].includes(origin.protocol)||origin.host!==req.headers.host||origin.username||origin.password)return json(res,403,{error:'Origin is not allowed.'});}
 if((req.headers['content-type']||'').split(';')[0].trim().toLowerCase()!=='application/json')return json(res,415,{error:'Use application/json for demo changes.'});
 let raw='';for await(const chunk of req){raw+=chunk;if(Buffer.byteLength(raw)>12000)return json(res,413,{error:'Request is too large.'});}let body;try{body=JSON.parse(raw);}catch{return json(res,400,{error:'Invalid JSON.'});}if(!body||typeof body!=='object'||Array.isArray(body))return json(res,400,{error:'Expected a JSON object.'});const d=read();
 if(url.pathname==='/api/requests'){const title=text(body.title),company=text(body.company),service=text(body.service);if(!title||!company||!['Consulting','Audit','Inspection','Training'].includes(service))return json(res,400,{error:'Enter a title, sample company and valid service.'});const item={id:'REQ-'+Date.now(),title,company,service,status:'Requested',date:text(body.date,20)||'To be scheduled'};d.requests.unshift(item);save(d);return json(res,201,item);}
 if(url.pathname==='/api/findings'){const title=text(body.title),action=text(body.action),engagement=text(body.engagement);if(!title||!action||!d.requests.some(r=>r.id===engagement))return json(res,400,{error:'Choose an engagement and enter a finding and corrective action.'});const item={id:'F-'+Date.now(),title,action,engagement,severity:'Minor',status:'Open',history:[{date:new Date().toISOString(),status:'Open',note:'Sample corrective action added.'}]};d.findings.unshift(item);save(d);return json(res,201,item);}
 if(url.pathname==='/api/finding-status'){const item=d.findings.find(x=>x.id===body.id);if(!item||!['Open','In progress','Ready for review','Closed'].includes(body.status))return json(res,400,{error:'Invalid finding or status.'});item.status=body.status;item.history.push({date:new Date().toISOString(),status:body.status,note:text(body.note)||'Demo status updated.'});save(d);return json(res,200,item);}
 if(url.pathname==='/api/document-review'){const item=d.documents.find(x=>x.id===body.id);if(!item)return json(res,404,{error:'Document not found.'});item.status=item.status==='Approved'?'In review':'Approved';save(d);return json(res,200,item);}
 if(url.pathname==='/api/training-progress'){const item=d.training.find(x=>x.id===body.id);if(!item)return json(res,404,{error:'Course not found.'});item.progress=Math.min(100,item.progress+20);save(d);return json(res,200,item);}
 return json(res,404,{error:'Endpoint not found.'});}
 if(req.method!=='GET')return json(res,405,{error:'Method not allowed.'});const routes=new Map([['/','index.html'],['/app.js','app.js'],['/style.css','style.css']]);const name=routes.get(url.pathname);if(!name){res.writeHead(404);return res.end('Not found');}res.writeHead(200,{'Content-Type':name.endsWith('.js')?'text/javascript':name.endsWith('.css')?'text/css':'text/html','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});fs.createReadStream(path.join(root,'public',name)).pipe(res);
 }catch(e){console.error(e);json(res,500,{error:'The demo could not save this change. Please try again.'});}});
server.listen(Number(process.env.PORT||5180),'127.0.0.1',()=>console.log('TIEC demo portal http://127.0.0.1:'+server.address().port));
